### PR TITLE
Fixes camera movement trembling

### LINKED ISSUE #20: Fix camera movement
Camera needs fixing

### PR DESCRIPTION
**Pull request by rosaqq**
Closes #20 

Instead of constantly setting mouse pos to window center, uses GLFW_CURSOR_DISABLED in camera mode and sets raytracing to use window center instead of mouse pos in that mode.

### CODE REVIEW

File: src/main/java/net/sknv/game/Renderer.java [hunk 1]
```diff
@@ -152,7 +152,7 @@ public void render(Window window, MouseInput mouseInput, Camera camera, ArrayLis
         }
 
         if(!clickedItems.isEmpty()) {
-            Float d = cameraPos.distance(clickedItems.get(0).getPos());
+            float d = cameraPos.distance(clickedItems.get(0).getPos());
```
Comment (dffsa) [inline src/main/java/net/sknv/game/Renderer.java:155]: drogolho

**Review by dffsa — APPROVED** [review]
